### ISSUE TITLE
Stop processes with SIGKILL if SIGTERM is ignored

### ISSUE THREAD

**Issue by jawnsy** [tokuhirom/Proc-Guard#5]
By default, Proc::Guard will stop processes using `SIGTERM` [0], which can be handled by the process and thus enables it to clean up after itself.  However, as it can be ignored, it would be advisable to wait for some time (30 or 60 seconds is common), check if the process is still running, and follow up with `SIGKILL`, which will immediately terminate the process in a way that cannot be caught.

[0] https://metacpan.org/source/TOKUHIROM/Proc-Guard-0.07/lib/Proc/Guard.pm#L74

**Comment by tokuhirom** [comment]
If you want to timeout, you can use alarm().
